############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/en/"
weight = 1

[[main]]
name = "Blog"
url = "/en/blog"
weight = 2

[[main]]
weight = 3
name = "Pages"

[[main]]
parent = "Pages"
name = "Categories"
url = "/en/categories"

[[main]]
parent = "Pages"
name = "Tags"
url = "/en/tags"

# footer menu
[[footer]]
name = "Blog"
url = "/en/blog"
weight = 1

[[footer]]
name = "Privacy Policy"
url = "/en/privacy-policy"
weight = 2
